name: Build and Release

on:
  push:
    tags:
      - "v*"
  pull_request:
    branches: [main, "release/*"]

permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build Binary
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        arch: [amd64, arm64]
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: darwin

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Create dist directory
        run: mkdir -p dist

      - name: Build Binary
        env:
          GOOS: ${{ matrix.platform }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o dist/migraine-${{ matrix.platform }}-${{ matrix.arch }}
          cd dist && ln -s migraine-${{ matrix.platform }}-${{ matrix.arch }} mig-${{ matrix.platform }}-${{ matrix.arch }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: migraine-${{ matrix.platform }}-${{ matrix.arch }}
          path: |
            dist/migraine-${{ matrix.platform }}-${{ matrix.arch }}
            dist/mig-${{ matrix.platform }}-${{ matrix.arch }}
          compression-level: 9
          retention-days: 5

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Generate checksums
        run: |
          cd artifacts
          for file in migraine-*; do
            sha256sum "$file" >> ../checksums.txt
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/migraine-*
            checksums.txt
          name: Release ${{ github.ref_name }}
          body_path: ${{ github.workspace }}/CHANGELOG.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-homebrew:
    needs: release
    name: Update Homebrew Formula
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Calculate checksums
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          # Add sleep to ensure release assets are available
          sleep 45

          # Download the released binaries
          curl -LO "https://github.com/tesh254/migraine/releases/download/$VERSION/migraine-darwin-amd64"
          curl -LO "https://github.com/tesh254/migraine/releases/download/$VERSION/migraine-darwin-arm64"

          # Calculate SHA256 checksums
          echo "SHA256_INTEL=$(sha256sum migraine-darwin-amd64 | awk '{print $1}')" >> $GITHUB_ENV
          echo "SHA256_ARM=$(sha256sum migraine-darwin-arm64 | awk '{print $1}')" >> $GITHUB_ENV

      - name: Update Homebrew formula
        env:
          HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
        run: |
          # Clone the Homebrew tap repository
          git clone https://$HOMEBREW_TAP_TOKEN@github.com/tesh254/homebrew-migraine.git
          cd homebrew-migraine

          # Update the formula
          cat > migraine.rb << EOL
          class Migraine < Formula
            desc "A robust CLI tool used to organize and automate complex workflows with templated commands"
            homepage "https://github.com/tesh254/migraine"
            version "${VERSION#v}"

            on_macos do
              if Hardware::CPU.intel?
                url "https://github.com/tesh254/migraine/releases/download/${VERSION}/migraine-darwin-amd64"
                sha256 "$SHA256_INTEL"
              else
                url "https://github.com/tesh254/migraine/releases/download/${VERSION}/migraine-darwin-arm64"
                sha256 "$SHA256_ARM"
              end
            end

            def install
              bin.install Dir["migraine-*"][0] => "migraine"
              # Create the mig alias
              bin.install_symlink "migraine" => "mig"
            end

            test do
              system "#{bin}/migraine", "--version"
              system "#{bin}/mig", "--version"
            end
          end
          EOL

          # Commit and push the changes
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add migraine.rb
          git commit -m "Update migraine to ${VERSION}"
          git push
